#!/bin/bash
# ========================================
# 🚀 QUICK START: Docker Management
# ========================================

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  🐳 DOCKER MANAGEMENT - SCHNELLSTART                           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 VERFÜGBARE TOOLS:"
echo ""
echo "  1️⃣  Interaktives Management-Menü:"
echo "      ./docker-manager.sh"
echo ""
echo "  2️⃣  Live-Logs im Terminal:"
echo "      ./docker-logs-live.sh                # Alle Container"
echo "      ./docker-logs-live.sh python-backend # Nur Python"
echo "      ./docker-logs-live.sh kotlin-api     # Nur Kotlin"
echo ""
echo "  3️⃣  Web-Dashboard (Passwort-geschützt):"
echo "      URL:      http://localhost:8501"
echo "      Passwort: admin123"
echo "      Features: Container neustarten, Logs anzeigen, Analytics"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "🔧 HÄUFIGE BEFEHLE:"
echo ""
echo "  Status anzeigen:"
echo "    docker compose ps"
echo ""
echo "  Container neustarten:"
echo "    docker compose restart python-backend"
echo "    docker compose restart kotlin-api"
echo "    docker compose restart"  # alle
echo ""
echo "  Logs anzeigen:"
echo "    docker compose logs --tail=100 python-backend"
echo "    docker compose logs -f python-backend  # Live"
echo ""
echo "  Container neu bauen:"
echo "    docker compose up -d --build"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "📚 Dokumentation: DOCKER_MANAGEMENT_GUIDE.md"
echo ""
