spring.application.name=kotlin-api

# Hinzufügen des PostgreSQL-Dialekts zur Fehlerbehebung
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Vergewissern Sie sich, dass diese drei Zeilen exakt so gesetzt sind:
# docker und localhost finden sich nicht
#spring.datasource.url=jdbc:postgresql://localhost:5432/jobmining_db
# ${DB_HOST:localhost} bedeutet: Nimm die Environment-Variable DB_HOST; wenn sie nicht da ist (Start in IntelliJ), nimm 'localhost'.
# Der Port ist 5432.
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/jobmining_db
spring.datasource.username=jobmining_user
spring.datasource.password=secret_password

spring.jpa.hibernate.ddl-auto=update
